name: turbodbc
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pyarrow>=7.0,<18
  - sel(unix): unixodbc
  - c-compiler
  - cxx-compiler
  - gmock=1.10.0
  - gtest
  - boost-cpp
  - cmake
  - pkg-config
  - ninja
  - pytest
  - numpy>=1.20
  - pybind11
  - simdutf
